### ISSUE TITLE
features/song_spec.rb needs "require 'rails_helper'" at the top

### ISSUE THREAD

**Issue by bentonwong** [learn-co-curriculum/refactoring-views-with-helpers-lab#10]
The test will not run without require 'rails_helper' at the top.  A student kept getting an uninitialized constant error for those test.  We added require 'rails_helper' to the top of the test and the test works now.

**Comment by DanielSeehausen** [comment]
Hi there @bentonwong,

I'm having difficulty reproducing the issue (cloned down, bundle installed, ran rspec with no problems), so I'm going to close it for now. I have added require 'rails_helper' to the only test file missing it, but am unsure if this addresses your problem as it does not change behavior on my end.

If you can provide further detail (which test/test file?) about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
