### ISSUE TITLE
Requires Gemfile Update for Ruby 2.6.1

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/refactoring-views-with-helpers-lab#13]
Ruby 2.6.1 creates errors when running with Rails 4.2.x.
Students using 2.6.1 are getting errors when running learn.

Solution: upgrade `Gemfile` to a rails version > 5.0, ie
`gem 'rails', '5.0.7.1'`

Note that bundler has to be > 2.0.x with rails > 5.0

_Edit: Removing the version entirely should work as well_

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
