### ISSUE TITLE
No Build

### ISSUE THREAD

**Issue by arpethel** [learn-co-curriculum/refactoring-views-with-helpers-lab#14]
This lab takes so long to build that it times out and disconnects from the remote server.

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information, I'd be happy to take a second look!

As always, thanks for contributing! 💙
