### ISSUE TITLE
Code is missing from this lab when git clone in Learn IDE

### ISSUE THREAD

**Issue by lennhy** [learn-co-curriculum/refactoring-views-with-helpers-lab#9]

**Comment by DanielSeehausen** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local and IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
